version: '3'
services:
  ensek:
    build:
      context: .
      dockerfile: ./src/App/Dockerfile
    networks:
      - ensek
    ports:
      - 5000:80
      - 5001:443
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ensek
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - ensek
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

networks:
  ensek:
    name: ensek
    external: true